[package]
name = "cherry-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.24.0"
lazy_static = "1.4.0"
ron = "0.7.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.31"
